# Generated by Django 2.1.8 on 2019-04-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Postcodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postcodes',
            new_name='Postcode',
        ),
    ]
